class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?

    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do
# Authentication routes generated by authentication generator
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  delete 'sign_out', to: 'sessions#destroy', as: :sign_out
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resource :session, only: [:new, :show, :destroy] do
    get :devices, on: :member
    delete :destroy_one, on: :member
  end
  resources :registrations, only: [:new, :create]
  resource  :password, only: [:edit, :update]

  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end

  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"

  resource :invitation, only: [:new, :create]

  # Profile routes
  resource :profile, only: [:show, :edit, :update], controller: 'profiles' do
    member do
      get :edit_password
      patch :update_password
    end
  end

  # API routes for curl-friendly authentication
  namespace :api do
    namespace :v1 do
      post 'login', to: 'sessions#login'
      delete 'logout', to: 'sessions#destroy'
      post 'sign_up', to: 'registrations#create'
      resource :profile, only: [:show, :update], controller: 'profiles'
      put 'password', to: 'profiles#update_password'
    end
  end

  # Authentication routes generated end

  # Routes for my_books generated by controller generator
  resources :my_books, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      patch :move_article
      patch :change_cover
    end
    resources :chapters, only: [:create, :edit, :update, :destroy], controller: 'my_books/chapters'
  end
  
  # Update articles within books context
  namespace :my_books do
    resources :articles, only: [:update]
  end
  # End routes for my_books

  # Routes for books generated by controller generator
  # Commented out - books list page is not needed
  # resources :books, only: [:index, :show]
  # End routes for books

  # Writing interface - requires authentication
  get 'write', to: 'articles#index', as: :write
  get 'write/history', to: 'articles#history', as: :write_history
  
  # Routes for articles (viewing completed articles)
  resources :articles, only: [:show] do
    member do
      post :archive
    end
  end
  
  # API routes for book/chapter selection
  namespace :api do
    resources :books, only: [:index] do
      resources :chapters, only: [:index]
    end
  end

  root 'home#index'
  
  # Static pages
  get 'help', to: 'pages#help', as: :help
  get 'privacy', to: 'pages#privacy', as: :privacy
  get 'terms', to: 'pages#terms', as: :terms

  # Do not write business logic at admin dashboard
  namespace :admin do
    resources :users, only: [:index, :show]
    resources :chapters
    resources :books
    resources :personas
    resources :admin_oplogs, only: [:index, :show]
    resources :administrators
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    # Mount GoodJob dashboard
    mount GoodJob::Engine => 'good_job', :constraints => AdminConstraint.new

    root to: 'dashboard#index'
  end

  mount ActionCable.server => '/cable'

  # Catch-all route for all 404 errors - MUST be last
  match '*path', to: 'application#handle_routing_error', via: :all,
    constraints: lambda { |request|
      !request.path.start_with?('/rails/active_storage')
    }
end
