class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?

    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do
  # Routes for my_books generated by controller generator
  resources :my_books, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    member do
      patch :move_article
      patch :change_cover
    end
    resources :chapters, only: [:create, :edit, :update, :destroy], controller: 'my_books/chapters'
  end
  
  # Update articles within books context
  namespace :my_books do
    resources :articles, only: [:update]
  end
  # End routes for my_books

  # Routes for books generated by controller generator
  # Commented out - books list page is not needed
  # resources :books, only: [:index, :show]
  # End routes for books

  # Routes for articles
  resources :articles, only: [:index, :show] do
    collection do
      get :history
    end
    member do
      post :archive
    end
  end
  
  # API routes for book/chapter selection
  namespace :api do
    resources :books, only: [:index] do
      resources :chapters, only: [:index]
    end
  end

  root 'articles#index'

  # Do not write business logic at admin dashboard
  namespace :admin do
    resources :chapters
    resources :books
    resources :personas
    resources :admin_oplogs, only: [:index, :show]
    resources :administrators
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    # Mount GoodJob dashboard
    mount GoodJob::Engine => 'good_job', :constraints => AdminConstraint.new

    root to: 'dashboard#index'
  end

  mount ActionCable.server => '/cable'

  # Catch-all route for all 404 errors - MUST be last
  match '*path', to: 'application#handle_routing_error', via: :all,
    constraints: lambda { |request|
      !request.path.start_with?('/rails/active_storage')
    }
end
